### ISSUE TITLE
[ERROR] ImportError: No module named storage

### ISSUE THREAD

**Issue by Moltivie** [RIT-Expo16-CSE-Enfuegos/Lisa#3]
This is the error when trying to run the following command:
```console
import sys
```
ERROR:
```console
Traceback (most recent call last):
  File "Interface.py", line 14, in <module>
    import Interpreter
  File "C:\Users\User\Desktop\Lisa-master\Interpreter.py", line 30, in <module>
    class interpreter :
  File "C:\Users\User\Desktop\Lisa-master\Interpreter.py", line 32, in interpreter
    reply.init()
  File "C:\Users\User\Desktop\Lisa-master\reply_engine.py", line 13, in init
    database="database/database.db")
  File "C:\ProgramData\Anaconda2\lib\site-packages\chatterbot\chatterbot.py", line 39, in __init__
    utils.validate_adapter_class(storage_adapter, StorageAdapter)
  File "C:\ProgramData\Anaconda2\lib\site-packages\chatterbot\utils.py", line 64, in validate_adapter_class
    if not issubclass(import_module(validate_class), adapter_class):
  File "C:\ProgramData\Anaconda2\lib\site-packages\chatterbot\utils.py", line 15, in import_module
    module = importlib.import_module(module_path)
  File "C:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
```

**Comment by ParadoxZero** [comment]
Will look into it. Had made this long ago.

**Comment by Moltivie** [comment]
I'm going to stay tuned!
